name: dstractor_panel
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  meta: ^1.12.0
  equatable: ^2.0.5
  web_socket_channel: ^3.0.0
  split_view: ^3.2.1
  xinput_gamepad: ^1.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
